Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -46,8 +46,8 @@ jobs:
             done;
 
             CURRENT_CNT=$(echo ${CURRENT_COLLECTIONS} | awk -F ';' '{print NF}')
-            echo "Number of Postman collections: $CNT"
-            echo "Number of current collections: $CURRENT_CNT"
+            #echo "Number of Postman collections: $CNT"
+            #echo "Number of current collections: $CURRENT_CNT"
             #echo "Current collections: " 
             echo "" > /tmp/artifacts-tests         
             c_index=0
@@ -68,7 +68,7 @@ jobs:
                 if [ "$name" = "$cc" ]; then    
                   echo "Running Postman collection: ${name}..."            	
                   newman run https://api.getpostman.com/collections/$id?apikey=$API_KEY --environment https://api.getpostman.com/environments/$env_test?apikey=$API_KEY >> /tmp/artifacts-tests
-                  echo "Postman command exit code: " $?
+                  #echo "Postman command exit code: " $?
                   #echo "COLLECTION FOUND!!! ${cc}"
                 fi;                
                 cc_index=$(expr $cc_index + 1)
